name: Publish AzureFunc Artifact

on:
  page_build:
  release:
    types:
      - created

jobs:
  publish-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Add Garage Group NuGet Source
      run: >
        dotnet nuget add source ${{ vars.GG_NUGET_SOURCE_URL }}
        -n garage
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    - name: Restore AzureFunc
      run: dotnet restore ./src/*/AzureFunc.csproj

    - name: Build AzureFunc
      run: dotnet build ./src/*/AzureFunc.csproj --no-restore  -c Release

    - name: Publish AzureFunc
      run: dotnet publish ./src/*/AzureFunc.csproj --no-build  -c Release --output ./build

    - name: Get version
      id: get_version
      run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

    - name: Archive publish folder
      run: |
        cd ./build
        zip -r garage-group-platform-swagger-hub-azure-func-net8-${{ env.version }}.zip ./

    - name: Azure Loging
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_ARTIFACT }}

    - name: Upload to Azure Blob Storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az storage blob upload \
            --container-name artifacts \
            --file ./build/garage-group-platform-swagger-hub-azure-func-net8-${{ env.version }}.zip \
            --account-name startifactblob \
            --account-key ${{ secrets.AZURE_ACCOUNT_KEY_ARTIFACT }} \
      env:
        AZURE_STORAGE_ACCOUNT: startifactblob

    - name: Azure Logout
      uses: azure/CLI@v1
      with:
        inlineScript: az logout

  publish-latest:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Add Garage Group NuGet Source
      run: >
        dotnet nuget add source ${{ vars.GG_NUGET_SOURCE_URL }}
        -n ggroupp
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    - name: Restore AzureFunc
      run: dotnet restore ./src/*/AzureFunc.csproj

    - name: Build AzureFunc
      run: dotnet build ./src/*/AzureFunc.csproj --no-restore  -c Release

    - name: Publish AzureFunc
      run: dotnet publish ./src/*/AzureFunc.csproj --no-build  -c Release --output ./build

    - name: Archive publish folder
      run: |
        cd ./build
        zip -r garage-group-platform-swagger-hub-azure-func-net8-latest.zip ./

    - name: Azure Loging
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_ARTIFACT }}

    - name: Upload to Azure Blob Storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az storage blob upload \
            --container-name artifacts \
            --file ./build/garage-group-platform-swagger-hub-azure-func-net8-latest.zip \
            --account-name startifactblob \
            --account-key ${{ secrets.AZURE_ACCOUNT_KEY_ARTIFACT }} \
      env:
        AZURE_STORAGE_ACCOUNT: startifactblob

    - name: Azure Logout
      uses: azure/CLI@v1
      with:
        inlineScript: az logout